name: Deploy website on push to Telegramonic.com

on:
  push:
    branches: ['development']

jobs:
  setup_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build --if-present
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.telegramonic.com
          username: u392139545.github_deploy
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./
