name: Build

on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']

jobs:
  build_test_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build --if-present
      - name: Linting
        run: yarn lint
      - name: Test
        run: yarn test
